# Generated by Django 4.2.8 on 2024-01-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochod', '0008_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
